# Generated by Django 2.1.7 on 2019-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeid', models.PositiveIntegerField()),
                ('degree_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250, null=True)),
                ('supervisor', models.PositiveIntegerField()),
                ('student', models.PositiveIntegerField()),
                ('second_reader', models.PositiveIntegerField(null=True)),
                ('demodate', models.DateField(blank=True, verbose_name='Date')),
                ('demotime', models.TimeField(blank=True, verbose_name='Time')),
                ('demoorganiser', models.PositiveIntegerField(null=True)),
                ('demolocation', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.PositiveIntegerField()),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, null=True)),
                ('studentnumber', models.IntegerField()),
                ('degree', models.PositiveIntegerField()),
                ('year', models.CharField(max_length=9, null=True)),
                ('doing_compsci_project', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisorid', models.PositiveIntegerField()),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, null=True)),
                ('initials', models.CharField(max_length=30)),
                ('max_students_to_supervise', models.PositiveIntegerField(null=True)),
                ('max_students_to_second_read', models.PositiveIntegerField(null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('year_of_appointment', models.PositiveIntegerField(null=True)),
                ('username', models.CharField(max_length=40, null=True)),
                ('user_type', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
