# Generated by Django 2.1.5 on 2019-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisorid',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
