# Generated by Django 2.1.5 on 2019-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marking', '0002_auto_20190314_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='degree_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
