# Generated by Django 2.1.5 on 2019-03-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0003_auto_20190315_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readerOneHasMarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='readerOneMark',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='readerTWoHasMarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='readerTWoMark',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
