# Generated by Django 2.1.5 on 2019-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0004_auto_20190315_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowedDifferenceInMarks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
