# Generated by Django 2.1.5 on 2019-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0007_icsprojectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readerOne',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='readerTWo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
