# Generated by Django 2.0.3 on 2019-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0009_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
