# Generated by Django 2.0.3 on 2019-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0010_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.IntegerField()),
                ('description', models.CharField(max_length=10000)),
                ('defaultWeight', models.IntegerField(default=20)),
                ('weighted', models.BooleanField(default=True)),
                ('degreeId', models.IntegerField()),
                ('degreeName', models.CharField(max_length=200)),
                ('section', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
