# Generated by Django 2.0.3 on 2019-03-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0012_content_inputbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='orderOnPage',
            field=models.IntegerField(default=1),
        ),
    ]
