# Generated by Django 2.1.5 on 2019-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0013_content_orderonpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.PositiveIntegerField(default=33),
        ),
    ]
