# Generated by Django 2.1.5 on 2019-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0014_project_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readerOneEmail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='readerTWoEmail',
            field=models.CharField(default='', max_length=250),
        ),
    ]
