# Generated by Django 2.0.3 on 2019-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0015_auto_20190327_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
