# Generated by Django 2.0.3 on 2019-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0016_content_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
