# Generated by Django 2.0.3 on 2019-04-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0017_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PDF',
        ),
    ]
