# Generated by Django 2.1.5 on 2019-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0018_auto_20190405_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='differenceInMarks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
