# Generated by Django 2.1.7 on 2019-03-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('demoDate', models.DateField(blank=True, null=True)),
                ('demoTime', models.TimeField(blank=True, null=True)),
                ('demoLocation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('studentNumber', models.PositiveIntegerField()),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('initials', models.CharField(max_length=30)),
                ('max_students_to_supervise', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_students_to_second_read', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_appointment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('user_type', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['surname'], name='tracking_su_surname_1586f1_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['firstname'], name='tracking_su_firstna_bcf2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['initials'], name='tracking_su_initial_daa900_idx'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.Degree'),
        ),
        migrations.AddField(
            model_name='student',
            name='doingCompSciProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.Supervisor'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surname'], name='tracking_st_surname_ed694b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['firstName'], name='tracking_st_firstNa_a8148c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['studentNumber'], name='tracking_st_student_9d8f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['supervisor'], name='tracking_pr_supervi_1b6615_idx'),
        ),
    ]
