# Generated by Django 2.1.7 on 2019-03-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.Degree'),
        ),
    ]
