# Generated by Django 2.1.7 on 2019-03-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_student_degree'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='tracking_pr_supervi_1b6615_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
    ]
