# Generated by Django 2.1.7 on 2019-03-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to='tracking.Supervisor'),
        ),
    ]
