# Generated by Django 2.1.7 on 2019-03-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20190324_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='doingCompSciProject',
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Student'),
        ),
    ]
