# Generated by Django 2.1.7 on 2019-03-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20190324_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='doingCompSciProject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.Project'),
        ),
    ]
