# Generated by Django 2.1.7 on 2019-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_remove_project_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['degree'], name='tracking_st_degree__97497e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year'], name='tracking_st_year_f716bc_idx'),
        ),
    ]
