# Generated by Django 2.1.7 on 2019-03-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20190324_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondReader',
        ),
        migrations.AddField(
            model_name='project',
            name='demoOrganiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demoOrganiser', to='tracking.Supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='secondReader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondReader', to='tracking.Supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Student'),
        ),
    ]
