# Generated by Django 2.1.7 on 2019-03-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20190324_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='secondReader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondReader', to='tracking.Supervisor'),
        ),
    ]
