markingScheme = {'courseNumber': 33,
                 'courseName': 'Integrated Computer Science',
                 'year': 2003,
                 '1': {'outline': 'computerScience_outline1',
                       'input': 'computerScience_input1',
                       'title': 'Problem statement and motivation',
                       'defaultWeight': 20},
                 '2': {'outline': 'computerScience_outline2',
                       'input': 'computerScience_input2',
                       'title': 'reserach / literature review',
                       'defaultWeight': 20},
                 '3': {'outline': 'computerScience_outline3',
                       'input': 'computerScience_input3',
                       'title': 'technical content and execution mark',
                       'defaultWeight': 20},
                 '4': {'outline': 'computerScience_outline4',
                       'input': 'computerScience_input4',
                       'title': 'testing evaluation analysis conclusion mark',
                       'defaultWeight': 20},
                 '5': {'outline': 'computerScience_outline5',
                       'input': 'computerScience_input5',
                       'title': 'presentation and writing',
                       'defaultWeight': 20}}
